# Generated by Django 4.0.4 on 2022-06-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boglanish',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
